### ISSUE TITLE
Odoo 8  and 9

### ISSUE THREAD

**Issue by edwingonzales** [hparfr/odoo-ionic-sample#3]
Great app but I am getting "Function declared as capable of handling request of type 'json' but called with a request of type 'http' in the Odoo 8 and 9 logs". I have resolved the CORS issue but get stucked in this error.

**Comment by hparfr** [comment]
Never seen this issue.
Can you post here the request in curl format ?

**Comment by edwingonzales** [comment]
The problem is with the Ionic Lab. After installing my apk in my android device, it works but not in Ionic Lab. Thanks. If you have tried this with Oionic Lab and have a solution for this, please share with me your solution. Thanks.

**Comment by hparfr** [comment]
I don't use Ionic Lab.
I guess it's serving the files from a dedicated server:port and is subject to CORS.
You can try to use instead your browser and go through a reverse proxy (that's the setup is use for dev)

I suppose it's working on the device because the files are served from file// and are not subject to same origin policy.

**Comment by edwingonzales** [comment]
Thanks.
